"""Install MCPs from the community catalog.

Two entry points:

- :func:`install_from_catalog` — fetch one MCP folder from
  ``OtoDock/community-mcps`` GitHub tarball and install it. Used by the
  admin Browse Community → Install flow and, transitively, by
  the manager-request → admin-approve flow.
- :func:`install_from_extracted_folder` — shared install pipeline. Takes
  a folder with a ``manifest.json`` and runs: validate → copy/replace →
  ``mcp_installer.install_mcp`` (npm/pip/docker) → rollback on failure →
  refresh registry. Reused by the zip-upload endpoint
  (``POST /v1/admin/mcps/install``) so both code paths share the same
  rollback + .env-regen + manifest-rescan logic.
"""

from __future__ import annotations

import asyncio
import io
import json
import logging
import os
import re
import shutil
import tarfile
import tempfile
from pathlib import Path

from urllib.parse import urlsplit

import httpx
from fastapi import HTTPException

import config
from services.infra import path_confinement
from services.mcp import mcp_manifest_parse as _mmp
from services.mcp import mcp_manifest_types as _mt
from services.mcp import mcp_registry, mcp_installer

logger = logging.getLogger("claude-proxy.community-installer")

# GitHub tarball endpoint. Follows a 302 to a codeload CDN URL — httpx
# follows redirects by default. The whole repo is ~50KB right now; even at
# 10x growth it stays trivial to download for one install. The env override
# pairs with the registry and raw-base knobs of ``community_catalog`` (a
# local mirror serves all three or none).
CATALOG_TARBALL_URL = os.environ.get("OTODOCK_MCPS_CATALOG_TARBALL_URL") or (
    "https://api.github.com/repos/OtoDock/community-mcps/tarball/main"
)
TARBALL_FETCH_TIMEOUT_SECONDS = 30.0

# Runtime-only directories preserved across update (and over a remnant
# folder). node_modules / venv are expensive to rebuild; keys / config /
# screenshots are local state the catalog never knows about. ``patches/`` is
# catalog content (like ``skills/``): a stale local copy would be applied to
# every new ``node_modules`` and block updates once a failed patch fails the
# install, and a changed patch set drops ``node_modules`` too.
_PRESERVE_DIRS = {"node_modules", "venv", "keys", "config", "screenshots"}

# An incoming folder (catalog tarball or admin archive) is source content
# only: a repository, a dependency tree or a package-manager configuration
# inside it would steer or execute the install. The directories are refused
# at any depth; the root-level lock and config files are dropped (the proxy
# resolves its own lock and ships it to satellites).
_REFUSED_INCOMING_DIRS = frozenset({".git", "node_modules", "venv"})
_DROPPED_INCOMING_FILES = frozenset({
    "package-lock.json", "npm-shrinkwrap.json", "yarn.lock", "pnpm-lock.yaml",
    ".npmrc", "uv.toml", "pip.conf",
})

# Generated runtime FILES (root-level) preserved across an update so their state
# survives the file-replace. ``docker-compose.override.yml`` carries the T1 subnet
# pin — keep it so the MCP's bridge subnet stays stable across updates. (The Docker
# ``.env`` is regenerated by ``_inject_mcp_env`` each start, so it isn't listed.)
_PRESERVE_FILES = {"docker-compose.override.yml"}

# The bound on each package-manager step of an install (its whole run), the
# installer's own default. Past it the step is killed with everything it
# started and the install rolls back.
_INSTALL_TIMEOUT_SECONDS = mcp_installer.DEFAULT_INSTALL_TIMEOUT


# ---------------------------------------------------------------------------
# Progress + off-loop filesystem helpers
# ---------------------------------------------------------------------------

# Job-level progress callback: receives ``{phase, pct, message}`` dicts. Reuses
# mcp_installer's permissive shape (sync or async callable, or None). The admin
# catalog-install background task passes a closure that writes to
# ``core.credentials.catalog_install_registry``; every other caller passes ``None`` and is
# unaffected.
ProgressCb = mcp_installer.ProgressCb


async def _emit(progress_cb: ProgressCb, phase: str, pct: int, message: str) -> None:
    """Forward one job-level progress event to ``progress_cb``. Never raises —
    a bad progress sink must not fail an install."""
    if progress_cb is None:
        return
    try:
        r = progress_cb({"phase": phase, "pct": pct, "message": message})
        if asyncio.iscoroutine(r):
            await r
    except Exception:
        logger.exception("install progress_cb raised")


_RUNTIME_DIRS = {"node_modules", "venv"}


def _patch_set(folder: Path) -> dict[str, bytes]:
    """The ``patches/*.patch`` files the installer applies, by name."""
    patches = folder / "patches"
    if not patches.is_dir():
        return {}
    return {p.name: p.read_bytes() for p in sorted(patches.glob("*.patch")) if p.is_file()}


def _apply_extracted_files(
    mcp_root: Path, target_dir: Path, is_update: bool, backup_dir: Path | None,
    *, drop_runtime_dirs: bool = False,
) -> None:
    """Backup + copy/replace the extracted MCP files into place.

    Synchronous filesystem work — run via ``asyncio.to_thread`` so a large
    copytree/rmtree (the backup of an existing dir, which can hold a
    hundreds-of-MB ``node_modules``/``venv``) never stalls the event loop now
    that the install also runs as a background task. An existing folder, an
    installed MCP's (``is_update``) or a remnant (present with no registry
    entry: preserved data carried across a migration, a half-cleaned
    install), is copied to ``backup_dir`` first when one is given; then every
    item but the ``_PRESERVE_DIRS`` and ``_PRESERVE_FILES`` ones gives way to
    the incoming folder, so nothing the catalog does not ship (a hand-dropped
    ``patches/``) survives. ``drop_runtime_dirs`` (a source switch) removes
    ``node_modules`` and ``venv`` as well, so the new package installs clean
    and the backup still restores them; a different ``patches/*.patch`` set
    (names or bytes) removes ``node_modules``, since npm keeps an unchanged
    package version as it is, files an earlier patch changed included.
    Callers: the community install below and the skill package install
    (``skills_installer``).
    """
    if not target_dir.exists():
        shutil.copytree(mcp_root, target_dir)
        return
    drop = set(_RUNTIME_DIRS) if drop_runtime_dirs else set()
    if _patch_set(target_dir) != _patch_set(mcp_root):
        drop.add("node_modules")
    if backup_dir is not None:
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        try:
            shutil.copytree(target_dir, backup_dir)
        except BaseException:
            # A half-written backup must never be put back in place of the
            # intact folder by the caller's rollback.
            shutil.rmtree(backup_dir, ignore_errors=True)
            raise

    for item in list(target_dir.iterdir()):
        if item.name in drop:
            shutil.rmtree(item, ignore_errors=True)
            continue
        if item.name in _PRESERVE_DIRS or item.name in _PRESERVE_FILES:
            continue
        if item.is_dir() and not item.is_symlink():
            shutil.rmtree(item)
        else:
            item.unlink()

    for item in mcp_root.iterdir():
        dest = target_dir / item.name
        if item.is_dir():
            if item.name in _PRESERVE_DIRS and dest.exists():
                continue
            if dest.exists():
                shutil.rmtree(dest)
            shutil.copytree(item, dest)
        else:
            shutil.copy2(item, dest)


def _remnant_owner(target_dir: Path, mcp_name: str) -> str:
    """The other MCP an existing folder belongs to, or "": one a registered
    MCP lives in, or whose own manifest names another MCP. Synchronous."""
    real = target_dir.resolve()
    for name, manifest in mcp_registry.get_all_manifests().items():
        if name != mcp_name and Path(manifest.mcp_dir).resolve() == real:
            return name
    try:
        named = json.loads((target_dir / "manifest.json").read_text()).get("name")
    except (OSError, ValueError, AttributeError):
        return ""
    return named if isinstance(named, str) and named and named != mcp_name else ""


def _rollback_extracted_files(target_dir: Path, backup_dir: Path) -> None:
    """Restore the pre-update backup after a failed install. Synchronous —
    run via ``asyncio.to_thread``."""
    shutil.rmtree(target_dir, ignore_errors=True)
    shutil.move(str(backup_dir), str(target_dir))


# ---------------------------------------------------------------------------
# Source identity: what an update may never change without an uninstall
# ---------------------------------------------------------------------------

def _pep503(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _image_repository(image: str) -> str:
    """``ghcr.io/otodock/x:1.2@sha256:…`` → ``ghcr.io/otodock/x``; a port in
    the registry host survives (the tag colon is the one after the last
    slash)."""
    ref = image.split("@", 1)[0]
    head, sep, tail = ref.rpartition("/")
    if ":" in tail:
        tail = tail.split(":", 1)[0]
    return (head + sep + tail).lower()


def _git_identity(source: str) -> str | None:
    """``git+https://user@Host/r.git@ref#subdirectory=d`` →
    ``git+https://host/r#d``: the scheme and the host are the identity, the
    userinfo and the ref (a version) are not, and the subdirectory selects
    the package. ``None`` when the port is not a number or the fragment names
    more than one subdirectory (the identity cannot say which one is built)."""
    url, _, fragment = source.partition("#")
    parts = urlsplit(url)
    host = (parts.hostname or "").lower()
    try:
        port = parts.port
    except ValueError:
        return None
    if port:
        host = f"{host}:{port}"
    path = parts.path.rsplit("@", 1)[0].rstrip("/")
    if path.endswith(".git"):
        path = path[:-4]
    subdirs = [
        value for key, _, value in (piece.partition("=") for piece in fragment.split("&"))
        if key == "subdirectory"
    ]
    if len(subdirs) > 1:
        return None
    subdir = subdirs[0].strip("/") if subdirs else ""
    return f"{parts.scheme.lower()}://{host}{path}#{subdir}"


def source_identity(*, runtime, source, image, url_template) -> tuple[str, str]:
    """The pair an unattended update may never change: the registry and the
    package for a node/python MCP, the image repository for a container,
    the vendor host for a remote MCP. Versions, tags, refs and the free-text
    label of a container source are not part of it. Never raises."""
    rt = _mt.runtime_of(runtime if isinstance(runtime, str) else "")
    if rt is not None and rt.container:
        return "image", _image_repository(image if isinstance(image, str) else "")
    if not isinstance(source, str):
        return "unknown", repr(source)
    if source.startswith("remote:"):
        host = urlsplit(url_template if isinstance(url_template, str) else "").hostname
        return "remote", (host or "").lower()
    if not source:
        return "none", ""
    if source.startswith("git+"):
        ident = _git_identity(source)
        return ("git", ident) if ident is not None else ("unknown", repr(source))
    parsed = mcp_installer.parse_source(source)
    if parsed is None or parsed.registry not in ("npm", "pypi"):
        return "unknown", repr(source)
    if parsed.registry == "pypi":
        return "pypi", _pep503(parsed.package)
    return "npm", parsed.package


def source_display(kind: str, *, source, image, url_template) -> str:
    """The source as the gate's message and the switch dialog name it."""
    if kind == "image":
        return str(image or "(built from the folder)")
    if kind == "remote":
        return str(url_template or source)
    return str(source or "(no source)")


def _refuse_source_change(
    name: str, installed, incoming: dict, *, accepted: tuple[str, str] | None = None,
) -> None:
    """409 when ``incoming`` (the new manifest's server block) names another
    source identity than the installed manifest's, unless ``accepted`` names
    exactly that new identity: the admin's switch
    (``mcp_source_swap.switch``) passes the pair it approved, and a catalog
    that moved to a third source since is refused the same way. Nothing has
    been written yet when this runs."""
    old = source_identity(
        runtime=installed.runtime, source=installed.source,
        image=installed.image, url_template=installed.url_template,
    )
    new = source_identity(
        runtime=incoming.get("runtime"), source=incoming.get("source", ""),
        image=incoming.get("image", ""), url_template=incoming.get("url_template", ""),
    )
    if old == new:
        return
    shown_old = source_display(
        old[0], source=installed.source, image=installed.image,
        url_template=installed.url_template,
    )
    shown_new = source_display(
        new[0], source=incoming.get("source", ""), image=incoming.get("image", ""),
        url_template=incoming.get("url_template", ""),
    )
    if accepted is not None:
        if new == tuple(accepted):
            logger.info("Source switch of %s accepted: %s to %s", name, shown_old, shown_new)
            return
        raise HTTPException(
            409,
            f"The catalog source of `{name}` changed again since the check (now "
            f"`{shown_new}`). Run Check updates and look at the change again.",
        )
    logger.warning(
        "Update of %s refused: source changed from %s to %s", name, shown_old, shown_new,
    )
    raise HTTPException(
        409,
        f"Update refused: the source of `{name}` changed from `{shown_old}` to "
        f"`{shown_new}`. Run Check updates and switch it from the MCP Servers "
        "page (the switch keeps its settings and credentials), or uninstall it "
        "and install it again.",
    )


def _refuse_shipped_trees(mcp_root: Path) -> None:
    """400 when the incoming folder carries a repository or a dependency
    tree at any depth (a ``.git`` file counts: it points git at one)."""
    found = sorted(
        str(p.relative_to(mcp_root)) for p in mcp_root.rglob("*")
        if p.name in _REFUSED_INCOMING_DIRS
    )
    if found:
        raise HTTPException(
            400,
            "MCP archive must not contain a repository or a dependency tree "
            f"(.git, node_modules, venv). Found: {found}. The platform "
            "installs dependencies itself from `server.source`.",
        )


def _drop_package_manager_files(mcp_root: Path) -> None:
    for name in _DROPPED_INCOMING_FILES:
        p = mcp_root / name
        if p.is_file() or p.is_symlink():
            p.unlink()


def _check_incoming_tree(mcp_root: Path) -> dict:
    """The incoming folder's checks, then its parsed ``manifest.json``.

    Synchronous (it walks the whole incoming tree): run via
    ``asyncio.to_thread``. Raises ``HTTPException`` 400 on a shipped ``.env``,
    repository or dependency tree, a missing manifest or invalid JSON.
    """
    # `.env` files in the install archive have caused every credential leak
    # in the historical audit. Reject them: the platform generates Docker
    # MCP `.env` from manifest declarations, stdio MCPs receive env from the
    # session, and per-user/per-instance credentials live in the DB.
    env_files = [p for p in mcp_root.rglob(".env") if p.is_file()]
    if env_files:
        rel = sorted(str(p.relative_to(mcp_root)) for p in env_files)
        raise HTTPException(
            400,
            "MCP archive must not contain `.env` files. Found: "
            f"{rel}. Use `manifest.json` env declarations + DB credentials/"
            "instances layer for sensitive values. See "
            "https://github.com/OtoDock/community-mcps/blob/main/CONTRIBUTING.md "
            "for the env contract.",
        )
    _refuse_shipped_trees(mcp_root)
    _drop_package_manager_files(mcp_root)

    manifest_path = mcp_root / "manifest.json"
    if not manifest_path.is_file():
        raise HTTPException(400, "manifest.json not found in MCP folder")
    try:
        manifest_data = json.loads(manifest_path.read_text())
    except json.JSONDecodeError as e:
        raise HTTPException(400, f"Invalid manifest.json: {e}")

    # A catalog Python MCP installs from its ``server.source``, wheels only.
    # A requirements file in its folder would be built outside that rule (by
    # the startup venv bootstrap or a satellite's runtime reconcile), so it
    # never lands. A Docker MCP keeps its own: the image build reads it.
    server = manifest_data.get("server") if isinstance(manifest_data, dict) else None
    if isinstance(server, dict) and server.get("runtime") == _mt.RUNTIME_PYTHON:
        req = mcp_root / "requirements.txt"
        if req.is_file() or req.is_symlink():
            req.unlink()
    return manifest_data


def _check_incoming_compose(mcp_root: Path, mcp_name: str) -> None:
    """The Docker-Compose refusals, judged on the incoming folder so a refused
    compose never replaces an installed version. Synchronous: run via
    ``asyncio.to_thread``. A no-op on bare metal."""
    from core.config import deployment
    from services.mcp import compose_rewrite
    if not deployment.in_docker_compose():
        return
    try:
        incoming = _mmp._parse_manifest(mcp_root / "manifest.json")
        if incoming is None:
            raise ValueError("manifest.json could not be read")
        compose_rewrite.check_pull_compose(incoming)
    except ValueError as exc:
        raise HTTPException(
            400, f"'{mcp_name}' cannot be installed in Docker-Compose mode: {exc}",
        )


# ---------------------------------------------------------------------------
# Manifest validation — same rules as the zip-upload path used to enforce
# locally. Moved here so both flows share one source of truth.
# ---------------------------------------------------------------------------

def _validate_manifest(data: dict) -> list[str]:
    """Return a list of human-readable validation errors; empty = valid.

    Shape defects are errors too, never exceptions: this runs on catalog
    content and on admin uploads, and a 500 would hide the reason.
    """
    errors: list[str] = []
    for key in ("name", "label", "description", "version", "category", "server"):
        if key not in data:
            errors.append(f"Missing required field: {key}")
    cat = data.get("category", "")
    if "server" in data:
        s = data["server"]
        if not isinstance(s, dict):
            errors.append("server must be an object")
            s = {}
        source = s.get("source", "")
        if not isinstance(source, str):
            errors.append("server.source must be a string")
            source = ""
        if source.startswith("git+") and _git_identity(source) is None:
            errors.append(
                "server.source must name one repository: an invalid port or more "
                "than one subdirectory"
            )
        compose_file = s.get("docker_compose")
        if compose_file not in (None, ""):
            compose_error = _mmp.skill_file_error(compose_file)
            if compose_error is not None:
                errors.append(
                    f"server.docker_compose {compose_file!r} must be a relative "
                    f"path inside the MCP folder ({compose_error})"
                )
        if source.startswith("remote:"):
            # Vendor-hosted MCP (linear/slack/zoom …) — nothing runs locally,
            # so no runtime/command; the connection needs a URL and a
            # non-stdio transport instead.
            if not s.get("url_template"):
                errors.append("Missing server.url_template (remote MCP)")
            if s.get("transport", "stdio") == "stdio":
                errors.append("Remote MCPs must declare a non-stdio transport")
        elif s:
            if "runtime" not in s:
                errors.append("Missing server.runtime")
            rt = _mt.runtime_of(s.get("runtime"))
            if rt is not None and rt.installed:
                if "command" not in s:
                    errors.append("Missing server.command")
                # A community folder is installed from its package source;
                # without one, its bundled requirements would be built at
                # the next proxy start, outside the catalog's install path.
                if not source and cat == "community":
                    errors.append(
                        "Missing server.source (a community MCP whose runtime "
                        "installs on the host must name its package)"
                    )
            source_build = s.get("source_build", [])
            if source_build is None:
                source_build = []
            if not isinstance(source_build, list) or not all(
                isinstance(e, str) and _mmp.SOURCE_BUILD_RE.fullmatch(e) for e in source_build
            ):
                errors.append("server.source_build must be a list of package names")
    creds = data.get("credentials")
    oauth = creds.get("oauth") if isinstance(creds, dict) else None
    if isinstance(oauth, dict):
        # One provider id, one way of issuing tokens: judged against the
        # installed manifests (the parser sees one manifest at a time).
        conflict = mcp_registry.authorization_server_conflict(
            str(data.get("name", "")), oauth,
        )
        if conflict:
            errors.append(f"credentials.oauth: {conflict}")
    skills = data.get("skills", [])
    if skills is None:
        skills = []
    if not isinstance(skills, list):
        errors.append("skills must be a list")
        skills = []
    for sk in skills:
        if not isinstance(sk, dict):
            errors.append(f"skill entry {sk!r} must be an object")
            continue
        sid = sk.get("id")
        if not isinstance(sid, str) or not sid:
            errors.append(f"skill entry {sk!r} is missing a string id")
            continue
        file_error = _mmp.skill_file_error(sk.get("file"))
        if file_error is not None:
            errors.append(
                f"skill {sid}: file {sk.get('file')!r} must be a relative path "
                f"inside the MCP folder ({file_error})"
            )
        audience_error = _mmp.skill_audience_error(sk.get("audience", ""))
        if audience_error is not None:
            errors.append(f"skill {sid}: audience {audience_error}")
    replaces = data.get("replaces", [])
    if replaces is None:
        replaces = []
    if not isinstance(replaces, list):
        errors.append("replaces must be a list")
    else:
        for entry in replaces:
            entry_error = _mmp.replaces_entry_error(entry)
            if entry_error is not None:
                errors.append(f"replaces entry {entry!r} {entry_error}")
    name = data.get("name", "")
    if name and not all(c.isalnum() or c in "-_" for c in name):
        errors.append(f"Invalid name '{name}' — use alphanumeric, dash, underscore only")
    if cat and cat not in ("core", "custom", "community"):
        errors.append(f"Invalid category '{cat}' — must be core, custom, or community")
    return errors


# ---------------------------------------------------------------------------
# The package check — what the installer will say, without installing
# ---------------------------------------------------------------------------

_MASTER_KEY_TOKENS = ("${platform.api_key}", "${proxy_api_key}")
_ICON_SIZE = 256
_ICON_MAX_BYTES = 256 * 1024


def _icon_problem(path: Path) -> str | None:
    """Why ``icon.png`` is not the 256×256 PNG the catalog asks for; ``None``
    when it is (the signature and the IHDR chunk, no imaging library)."""
    try:
        size = path.stat().st_size
        with path.open("rb") as fh:
            head = fh.read(24)
    except OSError as exc:
        return f"cannot be read ({exc})"
    if size > _ICON_MAX_BYTES:
        return f"is {size} bytes (limit {_ICON_MAX_BYTES})"
    if head[:8] != b"\x89PNG\r\n\x1a\n" or head[12:16] != b"IHDR":
        return "is not a PNG"
    width = int.from_bytes(head[16:20], "big")
    height = int.from_bytes(head[20:24], "big")
    if (width, height) != (_ICON_SIZE, _ICON_SIZE):
        return f"is {width}x{height}, must be {_ICON_SIZE}x{_ICON_SIZE}"
    return None


def check_package(mcp_root: Path, *, skipped: list[str] | tuple[str, ...] = ()) -> dict:
    """What ``install_from_extracted_folder`` would refuse, drop or accept in
    ``mcp_root``, plus the catalog's conventions, without installing
    anything: ``{ok, errors, warnings, summary}``. The authoring check tool
    (``validate_mcp_package`` in mcps-mcp) runs it on a snapshot of the
    author's folder; ``skipped`` names the entries the snapshot left out
    (dotfiles, ``node_modules``, ``venv``), judged here since the copy never
    holds them. Synchronous: run it through ``asyncio.to_thread``."""
    from urllib.parse import urlsplit
    errors: list[str] = []
    warnings: list[str] = []

    for name in skipped:
        base = name.rsplit("/", 1)[-1]
        if base == ".env":
            errors.append(
                f"{name}: a .env file is refused at install; declare environment "
                "values in the manifest and keep secrets in instances or credentials",
            )
        elif base in _REFUSED_INCOMING_DIRS:
            errors.append(
                f"{name}: a {base} entry is refused at install; the platform "
                "installs dependencies itself from server.source",
            )
    for p in sorted(mcp_root.rglob("*")):
        rel = str(p.relative_to(mcp_root))
        if p.name == ".env" and p.is_file():
            errors.append(f"{rel}: a .env file is refused at install")
        elif p.name in _REFUSED_INCOMING_DIRS:
            errors.append(f"{rel}: a {p.name} entry is refused at install")
    for name in sorted(_DROPPED_INCOMING_FILES):
        if (mcp_root / name).exists():
            warnings.append(f"{name} is dropped at install (the platform resolves its own lock)")

    manifest_path = mcp_root / "manifest.json"
    if not manifest_path.is_file():
        errors.append("manifest.json not found at the package root")
        return {"ok": False, "errors": errors, "warnings": warnings, "summary": {}}
    try:
        raw = manifest_path.read_text()
        data = json.loads(raw)
    except (OSError, ValueError) as exc:
        errors.append(f"manifest.json is not valid JSON: {exc}")
        return {"ok": False, "errors": errors, "warnings": warnings, "summary": {}}
    if not isinstance(data, dict):
        errors.append("manifest.json must hold an object")
        return {"ok": False, "errors": errors, "warnings": warnings, "summary": {}}

    errors.extend(_validate_manifest(data))
    named = _mmp.agent_context_credential_tokens(data.get("agent_context"))
    if named:
        warnings.append(
            f"agent_context names {', '.join(named)}: no credential value enters "
            "a prompt, so each renders empty and a requires on one skips its block")
    server = data.get("server") if isinstance(data.get("server"), dict) else {}
    source = server.get("source", "") if isinstance(server.get("source", ""), str) else ""
    runtime = server.get("runtime", "")
    rt = _mt.runtime_of(runtime) if isinstance(runtime, str) else None
    remote = source.startswith("remote:")
    name = data.get("name", "")
    if isinstance(name, str) and name and not _is_safe_name(name):
        errors.append(f"name {name!r} must be lowercase letters, digits, dashes and underscores")
    if data.get("category") not in (None, "community"):
        errors.append("category must be \"community\" (core and custom ship with the platform)")
    if source and not remote and mcp_installer.parse_source(source) is None:
        errors.append(
            f"server.source {source!r} is not an accepted source (npm:<package>, "
            "pypi:<package>, git+<url>@<ref>, docker:<image>, remote:<host>)",
        )
    skills = data.get("skills") if isinstance(data.get("skills"), list) else []
    for sk in skills:
        if isinstance(sk, dict) and isinstance(sk.get("file"), str) and \
                _mmp.skill_file_error(sk["file"]) is None and \
                _mmp.resolve_skill_file(mcp_root, sk["file"]) is None:
            errors.append(f"skill {sk.get('id')}: file {sk['file']!r} is not a regular file inside the package")
    compose_file = server.get("docker_compose") or ""
    if rt is not None and rt.container:
        if not compose_file:
            errors.append("server.docker_compose must name the compose file of a docker MCP")
        elif isinstance(compose_file, str) and _mmp.skill_file_error(compose_file) is None and \
                _mmp.resolve_skill_file(mcp_root, compose_file) is None:
            errors.append(f"server.docker_compose {compose_file!r} is not a regular file inside the package")
        if not server.get("image"):
            warnings.append(
                "server.image is absent: the containerised deployment cannot build "
                "an image, so the package installs on bare metal only",
            )
        url_template = str(server.get("url_template") or "")
        if "${docker_mcp_host}" not in url_template:
            warnings.append(
                "server.url_template should be http://${docker_mcp_host}:${port}: a fixed "
                "host breaks the containerised deployment",
            )
        if not str(data.get("version") or ""):
            errors.append("version must be set for a docker MCP (the image tag)")
    if source.startswith("git+") and not str(data.get("version") or ""):
        errors.append("version must be set for a git+ source (the pinned ref)")
    if rt is not None and rt.installed and source and not source.startswith("git+"):
        parsed = mcp_installer.parse_source(source)
        if parsed is not None and parsed.version:
            warnings.append(
                f"server.source pins {parsed.version}: the catalog leaves node and "
                "python packages unpinned and the platform pins the installed version",
            )
    if rt is not None and rt.installed and runtime == _mt.RUNTIME_PYTHON and (mcp_root / "requirements.txt").is_file():
        warnings.append("requirements.txt is dropped at install: a python package installs from server.source")
    for block in ("env", "agent_env"):
        values = data.get(block)
        if isinstance(values, dict):
            for key in values:
                if str(key).startswith("OTO_") or str(key) in ("PROXY_URL", "PROXY_API_KEY"):
                    warnings.append(
                        f"{block}.{key}: the OTO_* set, PROXY_URL and PROXY_API_KEY are "
                        "injected by the platform and must not be declared",
                    )
    for token in _MASTER_KEY_TOKENS:
        if token in raw:
            errors.append(f"the manifest references the master key ({token}), which is never given to an MCP")
    if not (mcp_root / "README.md").is_file():
        warnings.append("README.md is missing: the catalog shows it in the install dialog")
    icon = mcp_root / "icon.png"
    if icon.is_file():
        problem = _icon_problem(icon)
        if problem:
            warnings.append(f"icon.png {problem}")
    if not str(data.get("author") or "").strip():
        warnings.append("author is missing: name the project whose server code the package wraps")
    author_url = str(data.get("author_url") or "")
    author_parts = urlsplit(author_url)
    if author_parts.scheme != "https" or not author_parts.netloc:
        warnings.append("author_url should be the https:// repository of the upstream project")
    if not errors:
        try:
            parsed_manifest = _mmp._parse_manifest(manifest_path)
        except ValueError as exc:
            errors.append(f"manifest block rejected: {exc}")
            parsed_manifest = None
        if parsed_manifest is None and not errors:
            errors.append("the manifest could not be parsed")
    if not errors and rt is not None and rt.container:
        try:
            _check_incoming_compose(mcp_root, str(name))
        except HTTPException as exc:
            errors.append(str(exc.detail))

    skills = [sk.get("id") for sk in skills if isinstance(sk, dict)]
    creds = data.get("credentials") if isinstance(data.get("credentials"), dict) else {}
    summary = {
        "name": name, "label": data.get("label", ""),
        "runtime": "remote" if remote and not runtime else runtime,
        "transport": server.get("transport", ""),
        "source": source, "version": data.get("version", ""),
        "credentials": creds.get("type", "none"),
        "instances": isinstance(data.get("instances"), dict),
        "skills": [s for s in skills if isinstance(s, str)],
        "host": urlsplit(str(server.get("url_template") or "")).hostname or "" if remote else "",
        "files": sum(1 for p in mcp_root.rglob("*") if p.is_file()),
    }
    return {"ok": not errors, "errors": errors, "warnings": warnings, "summary": summary}


# ---------------------------------------------------------------------------
# Folder install — shared between zip-upload and tarball-fetch
# ---------------------------------------------------------------------------

async def install_from_extracted_folder(
    mcp_root: Path, *, progress_cb: ProgressCb = None, install_version: str | None = None,
    accepted_source: tuple[str, str] | None = None, accepted_manifest_hash: str = "",
) -> dict:
    """Install or update an MCP from an already-extracted folder.

    The folder must contain a ``manifest.json`` at its root. Subdirectories
    listed in ``_PRESERVE_DIRS`` are kept across updates so a re-install
    doesn't blow away ``node_modules`` / ``venv`` / per-instance state. A
    folder present with no registry entry (a remnant) is backed up and
    replaced the same way and restored on failure; one that holds another MCP
    is refused (409) before any file moves.

    ``progress_cb`` (optional) receives job-level ``{phase, pct, message}``
    events through the install — used by the async admin-install background job
    to drive the dashboard progress bar. Default ``None`` leaves the zip-upload
    endpoint and any other caller unchanged.

    ``install_version`` (optional) pins the exact node/python version to install
    (the update path resolves the bounded target and passes it here). When
    unset, a fresh install resolves the catalog ``server.version_constraint`` (if
    any) to the latest in-bound version, installs an already-pinned ``source``
    verbatim, or installs the bare latest. Ignored for docker/git+.

    ``accepted_source`` (the admin's switch, ``mcp_source_swap.switch``) lets
    the incoming folder change the installed source identity to exactly that
    pair, and ``accepted_manifest_hash`` pins the catalog manifest the admin
    saw: a folder whose manifest hashes differently is refused (409) before
    any file moves. A switch drops ``node_modules`` and ``venv`` after the
    backup and stops a container the incoming runtime no longer has.

    Raises ``HTTPException`` on validation or install failure. Returns a
    dict matching the existing zip-upload endpoint's response shape so the
    frontend can reuse its install-result UI, plus ``container_started``
    (the auto-start's outcome for a container runtime, ``None`` otherwise).
    """
    manifest_data = await asyncio.to_thread(_check_incoming_tree, mcp_root)

    errors = _validate_manifest(manifest_data)
    if errors:
        raise HTTPException(400, f"Invalid manifest: {'; '.join(errors)}")
    # The lexical rule passed above; the file must also exist inside THIS
    # folder as a regular file (a link is judged by its target).
    for sk in manifest_data.get("skills") or []:
        if _mmp.resolve_skill_file(mcp_root, sk["file"]) is None:
            raise HTTPException(
                400,
                f"Invalid manifest: skill {sk['id']}: file {sk['file']!r} is "
                "not a regular file inside the MCP folder",
            )
    compose_file = manifest_data["server"].get("docker_compose") or ""
    rt = _mt.runtime_of(manifest_data["server"].get("runtime"))
    if rt is not None and rt.container and compose_file:
        if _mmp.resolve_skill_file(mcp_root, compose_file) is None:
            raise HTTPException(
                400,
                f"Invalid manifest: server.docker_compose {compose_file!r} is "
                "not a regular file inside the MCP folder",
            )

    mcp_name = manifest_data["name"]
    category = manifest_data["category"]
    runtime = manifest_data["server"].get("runtime", "")  # absent on remote MCPs
    source = manifest_data["server"].get("source", "")
    version = manifest_data.get("version", "unknown")

    if category != "community":
        raise HTTPException(
            400,
            "Only community MCPs can be installed via this path. Core and "
            "custom MCPs ship with the platform. (Skill packages install via "
            "the skills catalog.)",
        )

    target_parent = config.MCPS_DIR / category
    target_parent.mkdir(parents=True, exist_ok=True)

    existing = mcp_registry.get_manifest(mcp_name)
    is_update = existing is not None
    # Flat-namespace guards (mirrored in skills_installer): an MCP whose name
    # is an installed SKILL PACKAGE, or whose skills[] ids collide with
    # another provider's, is rejected up front — the registry scan would
    # otherwise warn-and-shadow nondeterministically.
    if existing is not None and existing.category == "skill":
        raise HTTPException(
            409,
            f"Name {mcp_name!r} is already an installed skill package — "
            "MCPs and skill packages share the flat registry namespace",
        )
    if existing is not None and existing.category != "community":
        raise HTTPException(
            409,
            f"Name {mcp_name!r} is already a {existing.category} MCP shipped "
            "with the platform",
        )
    if existing is not None:
        _refuse_source_change(
            mcp_name, existing.server, manifest_data["server"], accepted=accepted_source,
        )
    switching = accepted_source is not None and existing is not None
    if switching and accepted_manifest_hash:
        from services.community import community_catalog
        if community_catalog.normalized_manifest_hash(manifest_data) != accepted_manifest_hash:
            raise HTTPException(
                409,
                f"The catalog entry of `{mcp_name}` changed since the check. Run "
                "Check updates and look at the change again.",
            )
    for _sk in manifest_data.get("skills") or []:
        _provider = mcp_registry.find_skill_provider(_sk.get("id", ""))
        if _provider is not None and _provider.name != mcp_name:
            raise HTTPException(
                409,
                f"Skill id {_sk.get('id')!r} is already provided by "
                f"{_provider.name!r}",
            )
    if rt is not None and rt.container:
        await asyncio.to_thread(_check_incoming_compose, mcp_root, mcp_name)
    # A switch away from a container runtime stops the container now, while
    # its compose file is still in place; a container-to-container switch is
    # replaced by the force-recreate start below. Nothing is torn down before
    # the gate above has passed.
    stopped_container = None
    if switching and _mt.is_container(existing.server) and not (rt is not None and rt.container):
        from services.mcp import docker_manager
        await asyncio.to_thread(docker_manager.stop_container, existing)
        stopped_container = existing
    old_version = existing.version if existing else None
    # Snapshot the prior enabled state. On update we'll restore it post-scan;
    # on new install we'll force enabled=True so the admin doesn't have to
    # flip the platform-enable toggle after an explicit "install" action.
    prior_enabled = _existing_enabled_state(mcp_name) if is_update else None

    folder_name = existing.mcp_dir.name if is_update else re.sub(
        r"[^a-zA-Z0-9_-]", "-", mcp_name,
    )
    target_dir = target_parent / folder_name
    if not is_update and target_dir.exists():
        # A folder with no registry entry for this name is replaced like an
        # update below; one that belongs to another MCP is never touched.
        owner = await asyncio.to_thread(_remnant_owner, target_dir, mcp_name)
        if owner:
            raise HTTPException(
                409,
                f"The folder {target_dir.name!r} already holds the MCP {owner!r}. "
                "Uninstall it first, or install this MCP under another name.",
            )

    # An existing folder (an update, or a remnant): take a sibling backup for
    # rollback, then replace only the non-preserved files. On a new folder:
    # just copy. All synchronous FS work runs off the event loop (this
    # function can run as a background install task), so a large
    # copytree/rmtree can't stall the loop.
    await _emit(progress_cb, "prepare", 15, "Preparing files")
    backup_dir: Path | None = None
    if target_dir.exists():
        backup_dir = target_dir.with_suffix(".bak")
    async def _undo_teardown() -> None:
        # After a rollback the old compose file is back: the container a
        # switch stopped is started again, best effort, unless the MCP was
        # disabled and its container down on purpose.
        if stopped_container is None or prior_enabled is False:
            return
        from services.mcp import docker_manager
        try:
            await asyncio.to_thread(docker_manager.start_container, stopped_container)
        except Exception as exc:
            logger.warning("Restart of %s after a failed switch failed: %s", mcp_name, exc)

    try:
        await asyncio.to_thread(
            _apply_extracted_files, mcp_root, target_dir, is_update, backup_dir,
            drop_runtime_dirs=switching,
        )

        # Run the package install (npm / pip / docker). The shared
        # ``mcp_installer`` is the same one the satellite uses.
        install_log = ""
        install_ok = True
        resolved_version = ""
        container_started: bool | None = None
        # remote: MCPs are vendor-hosted — the folder copy above IS the install
        # (manifest registration only), so skip the package-install step.
        if source and not source.startswith("remote:"):
            # Effective install source for node/python. The catalog source is unpinned
            # (`npm:pkg` / `pypi:pkg`); pick the exact version to install:
            #   • install_version given (update path) → that version;
            #   • catalog declares a version_constraint (fresh install) → latest in-bound;
            #   • source already pinned (e.g. a zip upload `npm:pkg@1.0.0`) → as-is;
            #   • otherwise → bare source (install_mcp installs the latest).
            # docker/git+ are installed verbatim (constraint/install_version ignored).
            from services.mcp import mcp_updater
            parsed = mcp_installer.parse_source(source)
            effective_source = source
            if parsed and parsed.registry in ("npm", "pypi"):
                if install_version:
                    effective_source = f"{parsed.registry}:{parsed.package}@{install_version}"
                elif not parsed.version:
                    constraint = manifest_data["server"].get("version_constraint", "") or ""
                    if constraint:
                        target = await mcp_updater.resolve_latest_in_bound(
                            parsed.registry, parsed.package, constraint,
                        )
                        if not target:
                            if backup_dir and backup_dir.exists():
                                await asyncio.to_thread(
                                    _rollback_extracted_files, target_dir, backup_dir,
                                )
                            await _undo_teardown()
                            raise HTTPException(
                                502,
                                f"No published {parsed.registry} version of "
                                f"'{parsed.package}' satisfies the catalog version "
                                f"constraint {constraint!r}.",
                            )
                        effective_source = f"{parsed.registry}:{parsed.package}@{target}"

            # Map mcp_installer's intra-step pct (npm/venv/pip, 0-100) into the job's
            # 20-80 "installing dependencies" band. A no-op for docker — install_mcp
            # returns instantly there; the real docker work (pull/start) is below.
            async def _install_progress(ev: dict) -> None:
                sub = ev.get("pct") or 0
                mapped = 20 + int(sub * 0.6)
                await _emit(
                    progress_cb, "install", mapped,
                    ev.get("message") or ev.get("phase") or "Installing dependencies",
                )
            try:
                result = await mcp_installer.install_mcp(
                    target_dir, runtime, effective_source,
                    progress_cb=_install_progress,
                    uv_bin=_uv_bin_if_present(),
                    timeout=_INSTALL_TIMEOUT_SECONDS,
                    source_build=list(manifest_data["server"].get("source_build") or []),
                )
                install_ok, install_log = result.ok, result.log
                resolved_version = result.resolved_version
            except asyncio.TimeoutError as exc:
                install_ok, install_log = False, f"Install timed out: {exc}"

        if not install_ok:
            if backup_dir and backup_dir.exists():
                await asyncio.to_thread(_rollback_extracted_files, target_dir, backup_dir)
            await _undo_teardown()
            raise HTTPException(
                500,
                f"Install failed — rolled back.\n\n{install_log}",
            )
    except HTTPException:
        raise
    except Exception:
        # Anything the explicit paths above did not catch (a copy error, a
        # spawn failure): the folder and the container come back before the
        # error leaves, so a retry meets the install as it was.
        if backup_dir and backup_dir.exists():
            await asyncio.to_thread(_rollback_extracted_files, target_dir, backup_dir)
        await _undo_teardown()
        raise

    if backup_dir and backup_dir.exists():
        await asyncio.to_thread(shutil.rmtree, backup_dir, ignore_errors=True)

    # Pin the LOCAL manifest for unpinned node/python installs (the catalog
    # carries no version for these — see services/mcp/mcp_updater.pin_local_manifest).
    # Best-effort: the install already succeeded and the backup is gone, so a pin
    # write failure must not fail the install — it self-heals on the next update.
    parsed = mcp_installer.parse_source(source) if source else None
    if parsed and parsed.registry in ("npm", "pypi") and resolved_version:
        try:
            from services.mcp import mcp_updater
            await asyncio.to_thread(
                mcp_updater.pin_local_manifest,
                target_dir, parsed.registry, parsed.package, resolved_version,
            )
            version = resolved_version
        except Exception as exc:
            logger.warning("Failed to pin local manifest for %s: %s", mcp_name, exc)
    # Never surface an empty version (unpinned catalog manifest reports "");
    # a readback miss leaves it unpinned but the UI should still show something.
    version = version or "latest"

    # Pick up the new manifest in the in-process registry, then regenerate
    # the Docker .env so the container picks up current platform values
    # without waiting for a proxy restart or enable-toggle.
    mcp_registry.scan_manifests()

    # Auto-enable on new install. On update, restore whatever the admin had
    # previously chosen (scan_manifests defaults community→disabled, which
    # would silently re-disable an MCP that was already enabled). For Docker
    # MCPs the .env regeneration below also runs only when enabled, so order
    # matters.
    from storage.mcp import mcp_store
    if is_update and prior_enabled is not None:
        await asyncio.to_thread(mcp_store.set_mcp_enabled, mcp_name, prior_enabled)
    elif not is_update:
        await asyncio.to_thread(mcp_store.set_mcp_enabled, mcp_name, True)

    refreshed = mcp_registry.get_manifest(mcp_name)

    # Default a relay-capable OAuth MCP to the OtoDock hosted relay so it works
    # out of the box. Relay-capable = the manifest declares a top-level
    # ``hosted.oauth_app`` that is available; if the relay is available it should
    # be the default (that is the whole point — no BYO OAuth app needed). We
    # persist the explicit ``_hosted_service_mode`` value rather than relying on
    # the manifest-``default_mode`` fallback (some read paths skip that fallback,
    # which is why a fresh install otherwise lands on self-managed). Only set it
    # when the admin hasn't already chosen a mode — so this never clobbers an
    # explicit choice and is a safe no-op on update.
    if (
        refreshed
        and refreshed.hosted
        and refreshed.hosted.oauth_app
        and refreshed.hosted.oauth_app.available
    ):
        existing_mode = await asyncio.to_thread(
            mcp_store.get_mcp_config_value, mcp_name, "_hosted_service_mode"
        )
        if existing_mode is None:
            await asyncio.to_thread(
                mcp_store.set_mcp_config_value, mcp_name, "_hosted_service_mode", "hosted"
            )
            logger.info("Defaulted relay-capable MCP %s to hosted OAuth", mcp_name)

    if refreshed and _mt.is_container(refreshed.server):
        try:
            from services.mcp import docker_manager
            await asyncio.to_thread(docker_manager._inject_mcp_env, refreshed)
        except Exception as exc:
            logger.warning("Failed to populate .env after install for %s: %s", mcp_name, exc)
        # T2: write the pull-form rewrite now. Its refusals were already
        # judged on the incoming folder, before any file moved
        # (_check_incoming_compose); idempotent, a no-op on bare-metal T1.
        try:
            from services.mcp import compose_rewrite
            await asyncio.to_thread(compose_rewrite.ensure_pull_compose, refreshed)
        except ValueError as exc:
            raise HTTPException(
                400,
                f"'{mcp_name}' cannot be installed in Docker-Compose mode: {exc}",
            )
        except Exception as exc:
            logger.warning("Compose pre-rewrite skipped for %s: %s", mcp_name, exc)
        # T2 only: the boot-time startup_docker_mcps skips community Docker MCPs,
        # so a runtime install has no other trigger to actually start the pulled
        # container — start it here when the MCP is enabled. Best-effort: a slow
        # first pull or a transient failure doesn't fail the install (the admin
        # can retry via restart). T1 is unchanged — startup_docker_mcps / the
        # admin start it there.
        from core.config import deployment
        enabled_now = True if not is_update else bool(prior_enabled)
        # Auto-start the container after install on every self-host topology —
        # T1 bare-metal AND T2 socket-proxy; only cloud (external-pool) has no
        # local container. start_container pulls (or builds, T1 fallback) + brings
        # it up, so the slow opaque fetch shows as the "image" phase on both.
        if enabled_now and deployment.current_mode() != deployment.EXTERNAL_POOL:
            await _emit(
                progress_cb, "image", 40,
                "Fetching image — large images can take a few minutes…",
            )
            try:
                # On an UPDATE, force-recreate so the running container is
                # replaced; start_container refreshes the image either way (a
                # same-tag rebuild or moved tag wouldn't be re-pulled by a
                # plain recreate).
                started = await asyncio.to_thread(
                    docker_manager.start_container, refreshed,
                    force_recreate=is_update,
                )
                logger.info("Auto-start %s after install: ok=%s", mcp_name, started)
                container_started = bool(started)
            except Exception as exc:
                logger.warning("Auto-start of %s after install failed: %s", mcp_name, exc)
                container_started = False
            await _emit(progress_cb, "start", 90, "Starting container")

    await _emit(progress_cb, "finalize", 95, "Finalizing")
    return {
        "status": "updated" if is_update else "installed",
        "name": mcp_name,
        "version": version,
        "old_version": old_version,
        "runtime": runtime,
        "install_log": install_log,
        "container_started": container_started,
    }


def _uv_bin_if_present() -> str | None:
    """Return path to ``uv`` if present, else ``None``."""
    import os
    uv = os.path.expanduser("~/.local/bin/uv")
    return uv if os.path.isfile(uv) else None


def _existing_enabled_state(mcp_name: str) -> bool | None:
    """Return the current ``mcp_state.enabled`` for an MCP, or ``None`` if no row exists."""
    from storage.mcp import mcp_store
    state = mcp_store.get_mcp_state(mcp_name)
    return state.get("enabled") if state else None


# ---------------------------------------------------------------------------
# Catalog install — fetch from GitHub, then call the shared pipeline
# ---------------------------------------------------------------------------

async def install_from_catalog(
    name: str, *, progress_cb: ProgressCb = None, install_version: str | None = None,
    accepted_source: tuple[str, str] | None = None, accepted_manifest_hash: str = "",
) -> dict:
    """Download one MCP folder from ``OtoDock/community-mcps`` and install it.

    Fetches the whole-repo tarball (small — ~50KB at the time of writing),
    extracts just the ``<name>/`` subfolder, hands it to
    :func:`install_from_extracted_folder`. Raises ``HTTPException`` on fetch
    or install failure.

    ``progress_cb`` (optional) is threaded through for live install progress;
    default ``None`` leaves the manager-request/approve caller unchanged.
    ``install_version`` (optional) pins the exact node/python version to install
    (the converge-update path passes the bounded target). ``accepted_source``
    and ``accepted_manifest_hash`` are the admin's switch (see
    :func:`install_from_extracted_folder`).
    """
    if not _is_safe_name(name):
        # Defense-in-depth — endpoint also validates, but the path is built
        # below by string interpolation against the tarball entries, so any
        # callable into this function gets the same check.
        raise HTTPException(400, f"Invalid MCP name: {name!r}")

    from services.community import community_catalog
    try:
        registry = await community_catalog.fetch_registry()
        _entry = next(
            (e for e in registry.get("mcps", []) if e.get("name") == name),
            None,
        )
    except Exception:
        _entry = None
    if _entry is not None:
        community_catalog.require_platform_compat(
            name, _entry.get("platform_min_version"),
        )

    await _emit(progress_cb, "fetch", 5, "Downloading from catalog")
    tarball = await _fetch_catalog_tarball()

    tmp = Path(tempfile.mkdtemp(prefix="mcp-catalog-install-"))
    try:
        # Extract just the target MCP's folder. GitHub tarballs prefix every
        # path with ``<owner>-<repo>-<sha>/`` so we walk to find the entry
        # that matches ``<prefix>/<name>/``.
        mcp_root = await asyncio.to_thread(
            _extract_mcp_subfolder, tarball, name, tmp,
        )
        if mcp_root is None:
            raise HTTPException(
                404,
                f"MCP '{name}' not found in catalog tarball. The catalog may "
                "have been updated since the last list refresh.",
            )

        return await install_from_extracted_folder(
            mcp_root, progress_cb=progress_cb, install_version=install_version,
            accepted_source=accepted_source,
            accepted_manifest_hash=accepted_manifest_hash,
        )
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _is_safe_name(name: str) -> bool:
    """Allow only ``[a-z0-9_-]`` so a malicious name can't escape the
    tarball-extraction path or sneak ``..`` into target paths."""
    return bool(re.fullmatch(r"[a-z0-9][a-z0-9_-]*", name))


async def _fetch_catalog_tarball(url: str = CATALOG_TARBALL_URL) -> bytes:
    """GET a catalog repo tarball as raw bytes (community-mcps by default;
    the skills installer passes its own catalog URL)."""
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "otodock-platform/community-installer",
    }
    try:
        async with httpx.AsyncClient(
            timeout=TARBALL_FETCH_TIMEOUT_SECONDS,
            follow_redirects=True,
        ) as client:
            resp = await client.get(url, headers=headers)
        resp.raise_for_status()
        return resp.content
    except httpx.HTTPError as exc:
        raise HTTPException(
            502,
            f"Could not fetch community catalog tarball: {exc}. "
            "Check network access to api.github.com / codeload.github.com.",
        )


def _extract_mcp_subfolder(tarball: bytes, mcp_name: str, dest: Path) -> Path | None:
    """Extract the catalog folder for ``mcp_name`` from the repo tarball into ``dest``.

    The folder usually shares the MCP's name, but the authoritative id is the
    ``name`` inside each folder's ``manifest.json`` and the two can differ —
    the catalog folder ``workspace-mcp`` ships manifest name
    ``google-workspace`` — so when no folder matches the name directly, fall
    back to scanning the top-level manifests for the matching name. Returns
    the path to the extracted MCP folder, or ``None`` when neither lookup
    matches.
    """
    # Tarball layout: <owner>-<repo>-<sha>/<folder>/...
    with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as tf:
        # Detect the prefix dir from the first member.
        members = tf.getmembers()
        if not members:
            return None
        prefix = members[0].name.split("/", 1)[0]
        folder = mcp_name
        if not any(
            m.name == f"{prefix}/{folder}" or m.name.startswith(f"{prefix}/{folder}/")
            for m in members
        ):
            folder = _folder_for_manifest_name(tf, members, prefix, mcp_name)
            if folder is None:
                return None
        prefix_with_mcp = f"{prefix}/{folder}/"

        wanted: list[tarfile.TarInfo] = []
        for m in members:
            if m.name == f"{prefix}/{folder}" or m.name.startswith(prefix_with_mcp):
                # Strip the prefix from the entry name so extraction lands
                # under ``dest/`` directly with no nested ``<sha>/`` wrapper.
                stripped = m.name[len(prefix) + 1:]
                if not stripped:
                    continue
                # Path-traversal guard: a clean relative name, joined below
                # the destination (never the raw member name).
                if stripped.startswith("/"):
                    raise HTTPException(400, f"Invalid tarball entry: {m.name}")
                try:
                    stripped = path_confinement.normalize_rel_path(stripped)
                    target_path = path_confinement.join_under(dest, stripped)
                except path_confinement.PathOutsideRoot:
                    raise HTTPException(400, f"Invalid tarball entry: {m.name}")
                m_copy = tarfile.TarInfo(name=stripped)
                m_copy.type = m.type
                m_copy.mode = m.mode
                m_copy.uid = m.uid
                m_copy.gid = m.gid
                m_copy.size = m.size
                m_copy.mtime = m.mtime
                m_copy.linkname = m.linkname
                wanted.append(m_copy)
                # Extract right away while we still have the source member.
                src = tf.extractfile(m) if m.isfile() else None
                if m.isdir():
                    target_path.mkdir(parents=True, exist_ok=True)
                elif m.isfile() and src is not None:
                    target_path.parent.mkdir(parents=True, exist_ok=True)
                    with target_path.open("wb") as out:
                        shutil.copyfileobj(src, out)
                elif m.issym() or m.islnk():
                    # We don't expect symlinks in catalog MCPs. Skip rather
                    # than raise so a stray symlink doesn't block install.
                    logger.warning("Skipping link entry in catalog tarball: %s", m.name)

        if not wanted:
            return None

    mcp_dir = dest / folder
    return mcp_dir if mcp_dir.is_dir() else None


def _folder_for_manifest_name(
    tf: tarfile.TarFile, members: list, prefix: str, mcp_name: str,
) -> str | None:
    """Top-level tarball folder whose ``manifest.json`` declares ``name == mcp_name``."""
    for m in members:
        parts = m.name.split("/")
        if len(parts) == 3 and parts[2] == "manifest.json" and m.isfile():
            src = tf.extractfile(m)
            if src is None:
                continue
            try:
                data = json.loads(src.read().decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                continue
            if data.get("name") == mcp_name:
                return parts[1]
    return None


# ---------------------------------------------------------------------------
# Request orchestration — approve / reject / cancel
# ---------------------------------------------------------------------------

async def ensure_enabled_and_running(mcp_name: str) -> str:
    """Converge platform state after an approval: enabled + (Docker) running.

    ``approve_request`` marks a request ``installed`` even when the fetch was
    skipped because the manifest folder already existed on disk (repo-shipped
    ``mcps/community/*``, a previously disabled MCP, a rolled-back attempt).
    ``scan_manifests`` seeds community MCPs at ``enabled=False`` and nothing
    on that path enabled the MCP or started its container — the request
    landed ``installed`` while the MCP stayed invisible at runtime. An
    approval (queue approve, admin auto-approve, the instance-save retry
    sweep, the community-agent template cascade) is an explicit "make this
    usable" decision, so converge unconditionally; a platform-wide re-enable
    of a deliberately disabled MCP is surfaced in the returned note, never
    silent.

    Returns an annotation for the request's ``install_log`` ("" when there
    is nothing noteworthy). Never raises — start problems are recorded, not
    fatal, matching the installer's best-effort auto-start. Idempotent after
    a fresh ``install_from_catalog`` (env re-inject is idempotent and a
    running container is left alone).
    """
    from storage.mcp import mcp_store

    notes: list[str] = []
    prior = _existing_enabled_state(mcp_name)
    if prior is not True:
        await asyncio.to_thread(mcp_store.set_mcp_enabled, mcp_name, True)
        if prior is False:
            notes.append("Re-enabled platform-wide (was disabled).")

    manifest = mcp_registry.get_manifest(mcp_name)
    from core.config import deployment
    if (
        manifest is not None
        and _mt.is_container(manifest.server)
        and deployment.current_mode() != deployment.EXTERNAL_POOL
    ):
        from services.mcp import docker_manager
        try:
            await asyncio.to_thread(docker_manager._inject_mcp_env, manifest)
        except Exception as exc:
            logger.warning(".env refresh failed for %s: %s", mcp_name, exc)
        try:
            from services.mcp import compose_rewrite
            await asyncio.to_thread(compose_rewrite.ensure_pull_compose, manifest)
        except ValueError as exc:
            # Approval context records the problem instead of failing the
            # request; the direct-install route keeps its hard 400.
            notes.append(f"Compose rewrite failed: {exc}")
        except Exception as exc:
            logger.warning("Compose pre-rewrite skipped for %s: %s", mcp_name, exc)
        status = await asyncio.to_thread(
            docker_manager.get_container_status, manifest,
        )
        if status not in docker_manager.STARTED:
            try:
                started = await asyncio.to_thread(
                    docker_manager.start_container, manifest,
                )
                logger.info(
                    "Auto-start %s after approval: ok=%s", mcp_name, started,
                )
                if not started:
                    notes.append(
                        "Container did not start — check Admin → MCP Servers.",
                    )
            except Exception as exc:
                logger.warning(
                    "Auto-start of %s after approval failed: %s", mcp_name, exc,
                )
                notes.append(f"Container start failed: {exc}")
    return "\n".join(notes)


async def approve_request(
    request_id: int,
    admin_sub: str,
    admin_note: str = "",
    instance_id: int | None = None,
) -> dict:
    """Approve an assignment request: install if needed + enable for agent.

    Returns the updated request row. Status transitions:

    - ``pending → approved → installing → installed`` on success
    - ``pending → approved → installing → install_failed`` on install error
      (the admin can retry later via the same endpoint).

    The MCP is enabled for the requesting agent (``mcp_store.add_agent_mcp``)
    only after the install completes successfully. Notifies the requester
    once the request resolves.

    ``instance_id`` (explicit-mode MCPs only) pins the instance the agent is
    attached to; ``None`` keeps the automatic pick (catch-all / already
    attached / lowest-id). Validated BEFORE any status transition — a 400
    mid-cascade would strand the row in ``installing``, a state the
    transition table only exits via installed/install_failed. Consequently
    ``instance_id`` requires the MCP to already be installed and
    explicit-mode; for a not-yet-installed MCP the admin approves without it
    and the needs-instance retry offers the selector.
    """
    from storage.mcp import mcp_request_store
    from storage.mcp import mcp_store

    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["status"] not in mcp_request_store.APPROVABLE:
        raise HTTPException(
            409,
            f"Cannot approve request in status {req['status']!r}",
        )

    if instance_id is not None:
        manifest = mcp_registry.get_manifest(req["mcp_name"])
        if manifest is None or getattr(manifest, "assignment_mode", "auto") != "explicit":
            raise HTTPException(
                400,
                "instance_id only applies to installed explicit-mode MCPs "
                f"('{req['mcp_name']}' is "
                f"{'not installed' if manifest is None else 'auto-mode'})",
            )
        _instances = await asyncio.to_thread(
            mcp_store.get_mcp_instances, req["mcp_name"],
        )
        if not any(int(i["id"]) == instance_id for i in _instances):
            raise HTTPException(
                400,
                f"Instance {instance_id} does not belong to MCP "
                f"'{req['mcp_name']}'",
            )

    # pending → approved → installing in one shot (avoid two notifications).
    if req["status"] == mcp_request_store.PENDING:
        await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, mcp_request_store.APPROVED, resolved_by=admin_sub, admin_note=admin_note,
        )
    req = await asyncio.to_thread(
        mcp_request_store.update_status, request_id, mcp_request_store.INSTALLING,
    )

    mcp_name = req["mcp_name"]
    agent_slug = req["agent_slug"]
    kind = req.get("kind") or "mcp"

    install_log = ""
    install_failed_msg: str | None = None
    try:
        # Skip the install when the MCP is already on disk and at the current
        # catalog version — the registry's ``get_manifest`` returns ``None``
        # only when the folder is absent. Serialize on the per-MCP install lock
        # so a concurrent direct admin install of the same MCP can't race this
        # on the install dir; re-check inside the lock (the other install may
        # have just landed it while we waited, in which case we no-op).
        from core.credentials import catalog_install_registry
        async with catalog_install_registry.lock_for(mcp_name):
            if mcp_registry.get_manifest(mcp_name) is None:
                if kind == "skill":
                    from services.community import skills_installer
                    install_result = await (
                        skills_installer.install_skill_package_from_catalog(mcp_name)
                    )
                else:
                    install_result = await install_from_catalog(mcp_name)
                install_log = install_result.get("install_log", "")
            else:
                install_log = "Already installed — skipping fetch + dependency install."
    except HTTPException as exc:
        install_failed_msg = exc.detail if isinstance(exc.detail, str) else str(exc.detail)
    except Exception as exc:
        logger.exception("Unexpected install error for %s", mcp_name)
        install_failed_msg = f"{type(exc).__name__}: {exc}"

    if install_failed_msg:
        updated = await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, mcp_request_store.INSTALL_FAILED,
            install_log=install_failed_msg,
        )
        # ``install_failed`` is non-terminal (admin may retry) — don't fire
        # the batch-complete roll-up here; only the per-request failure
        # notification, which the batched path also wants to receive so the
        # admin sees the error inline.
        await _notify_request_failed(updated)
        return updated

    # Install OK → converge platform state. The skip branch above never
    # enabled the MCP or started its container ("manifest on disk" is not
    # "enabled and running"), so an approved repo-shipped or previously
    # disabled MCP would otherwise stay invisible at runtime.
    converge_note = await ensure_enabled_and_running(mcp_name)
    if converge_note:
        install_log = (install_log + "\n" if install_log else "") + converge_note

    # Assign the MCP to the agent. ``add_agent_mcp`` is idempotent so a
    # re-request after a previous installed state is safe.
    await asyncio.to_thread(mcp_store.add_agent_mcp, agent_slug, mcp_name)

    # Seed agent_skills rows for the assignment (idempotent), mirroring the
    # manager-enable path — without this an approved MCP's/package's skills
    # have no rows for the Skills tab to toggle until the next manual save.
    _m = mcp_registry.get_manifest(mcp_name)
    for _skill in getattr(_m, "skills", None) or []:
        await asyncio.to_thread(
            mcp_store.ensure_agent_skill,
            agent_slug, _skill.id, True, _skill.default_exclude_from,
        )

    # For explicit-mode MCPs (prometheus, ssh-server, unifi-network, etc.),
    # the manager-enabled flag alone isn't enough — the runtime only
    # delivers env to an agent if at least one ``mcp_instances`` row
    # authorizes them. Make sure that's true before declaring success.
    instance_status, instance_detail = await asyncio.to_thread(
        _ensure_agent_authorized_for_instance_mcp, mcp_name, agent_slug,
        instance_id,
    )
    if instance_status == "no_instances":
        # Roll the agent_mcps assignment back so the manager UI doesn't
        # show a non-functional row. The install itself is fine; only
        # per-agent authorization is missing.
        await asyncio.to_thread(mcp_store.remove_agent_mcp, agent_slug, mcp_name)
        admin_guidance = (
            f"MCP '{mcp_name}' requires an instance configuration before it "
            f"can be authorized for an agent. Create an instance via "
            f"Admin → MCP Servers → {mcp_name} → Instances (give it credentials "
            f"and optionally tick 'Assign to all agents'), then retry this "
            f"approval."
        )
        updated = await asyncio.to_thread(
            mcp_request_store.update_status,
            request_id, mcp_request_store.INSTALL_FAILED,
            install_log=admin_guidance,
        )
        await _notify_request_failed(updated)
        return updated

    if instance_detail:
        install_log = (install_log + "\n" if install_log else "") + instance_detail

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, mcp_request_store.INSTALLED,
        resolved_by=admin_sub,
        install_log=install_log,
    )
    # Batched rows: suppress the per-request approve notification — the
    # requester gets a single roll-up via _maybe_notify_batch_complete once
    # every row in the batch reaches a terminal state.
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    else:
        await _notify_request_approved(updated)
    return updated


def _ensure_agent_authorized_for_instance_mcp(
    mcp_name: str, agent_slug: str, instance_id: int | None = None,
) -> tuple[str, str]:
    """Make sure an explicit-mode MCP authorizes ``agent_slug`` via at least one
    instance. No-op for non-explicit (auto-mode) MCPs.

    Returns (status, human_log) where status is one of:

    - ``"not_applicable"`` — MCP is auto-mode; nothing to do.
    - ``"added_to_selected"`` — admin chose an instance on approval; the
      agent was attached to exactly that one. An explicit choice wins over
      the catch-all/already-attached shortcuts — the admin said where the
      agent goes. (The id was validated against this MCP's instances before
      any status transition, so a vanished instance here means it was
      deleted mid-approve — that falls through to the automatic path.)
    - ``"assigned_to_all"`` — a catch-all instance already authorizes everyone.
    - ``"already_authorized"`` — agent was already in some instance's list.
    - ``"added_to_first"`` — agent was attached to the lowest-id instance
      (matches the runtime precedence in
      :func:`mcp_store.get_instance_for_agent_env_delivery`). Admin can move
      the agent to a different instance via the Instances UI if desired.
    - ``"no_instances"`` — explicit-mode MCP with zero instances. Caller
      should treat this as a soft failure and prompt the admin to create
      one before retrying.

    The ``human_log`` is a one-line description suitable for appending to
    the request's ``install_log``.
    """
    from storage.mcp import mcp_store

    manifest = mcp_registry.get_manifest(mcp_name)
    # ``getattr`` with default so test-stub manifests (bare ``object()``)
    # naturally fall through to "not applicable" rather than raising.
    if not manifest or getattr(manifest, "assignment_mode", "auto") != "explicit":
        return ("not_applicable", "")

    instances = mcp_store.get_mcp_instances(mcp_name)
    if not instances:
        return ("no_instances", "")

    if instance_id is not None:
        chosen = next(
            (i for i in instances if int(i["id"]) == instance_id), None,
        )
        if chosen is not None:
            mcp_store.add_agent_to_instance(chosen["id"], agent_slug)
            return (
                "added_to_selected",
                f"Attached agent to instance '{chosen['instance_name']}' "
                f"(admin-selected on approval).",
            )
        # Deleted between validation and here — automatic path below.

    if any(i["assigned_to_all"] for i in instances):
        return ("assigned_to_all", f"Authorized via catch-all instance.")

    if any(agent_slug in i["agents"] for i in instances):
        return ("already_authorized", f"Agent already attached to an instance.")

    target = sorted(instances, key=lambda i: i["id"])[0]
    mcp_store.add_agent_to_instance(target["id"], agent_slug)
    return (
        "added_to_first",
        f"Attached agent to instance '{target['instance_name']}' "
        f"(lowest id; admin can reassign via Instances UI).",
    )


async def reject_request(request_id: int, admin_sub: str, admin_note: str = "") -> dict:
    """Reject a pending request; notifies the requester with the admin's note."""
    from storage.mcp import mcp_request_store
    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["status"] != mcp_request_store.PENDING:
        raise HTTPException(409, f"Cannot reject request in status {req['status']!r}")

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, mcp_request_store.REJECTED,
        resolved_by=admin_sub, admin_note=admin_note,
    )
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    else:
        await _notify_request_rejected(updated)
    return updated


async def cancel_request(request_id: int, user_sub: str) -> dict:
    """Cancel an open pending request. Only the original requester may cancel."""
    from storage.mcp import mcp_request_store
    req = await asyncio.to_thread(mcp_request_store.get_request, request_id)
    if req is None:
        raise HTTPException(404, f"Request {request_id} not found")
    if req["requested_by"] != user_sub:
        raise HTTPException(403, "Only the original requester can cancel")
    if req["status"] != mcp_request_store.PENDING:
        raise HTTPException(409, f"Cannot cancel request in status {req['status']!r}")

    updated = await asyncio.to_thread(
        mcp_request_store.update_status,
        request_id, mcp_request_store.CANCELLED,
        resolved_by=user_sub,
    )
    if updated.get("batch_id"):
        await _maybe_notify_batch_complete(updated)
    return updated


# ---------------------------------------------------------------------------
# Notification dispatch
# ---------------------------------------------------------------------------

async def notify_request_created(request: dict) -> None:
    """Notify every admin that a new MCP request landed.

    Batched-request rows (``batch_id`` populated by a community-agent install
    cascade) are skipped — the caller will fire a single combined
    notification via :func:`notify_batch_created`. Lone requests (e.g. via
    ``mcps-mcp`` or the Browse drawer) still fire one notification per admin
    per request, the legacy behavior."""
    if request.get("batch_id"):
        return
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    if not admin_subs:
        return
    from services.notifications import notification_manager
    requester = _format_requester(request)
    reason = (request.get("reason") or "").strip()
    reason_line = f"\n\n_Reason:_ {reason}" if reason else ""
    for sub in admin_subs:
        await notification_manager.fire_notification(
            title="MCP request pending",
            body=(
                f"{requester} requested **{request['mcp_name']}** for agent "
                f"**{request['agent_slug']}**. Review in Admin → MCP Requests."
                f"{reason_line}"
            ),
            severity="info",
            scope="user",
            target=sub,
            source="mcp",
            source_id=str(request["id"]),
        )


async def notify_batch_created(
    batch_id: str,
    requester_sub: str,
    target_agent_slug: str,
    template_slug: str,
) -> None:
    """Fire one combined notification per admin for a community-agent
    install batch. Skips the requester if they happen to be an admin (admin
    self-installs auto-approve inline anyway — they don't need to be told).
    """
    from storage.mcp import mcp_request_store

    rows = await asyncio.to_thread(mcp_request_store.list_requests_by_batch, batch_id)
    if not rows:
        return
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    admin_subs = [s for s in admin_subs if s != requester_sub]
    if not admin_subs:
        return
    from services.notifications import notification_manager
    requester = _format_requester(rows[0])
    summary_lines = []
    for row in rows:
        reason_blurb = f" — _{row['reason']}_" if (row.get("reason") or "").strip() else ""
        summary_lines.append(f"- **{row['mcp_name']}**{reason_blurb}")
    body = (
        f"{requester} wants to install community agent **{template_slug}** "
        f"as `{target_agent_slug}`. This requires admin action on "
        f"{len(rows)} MCP{'s' if len(rows) != 1 else ''}:\n\n"
        + "\n".join(summary_lines)
        + "\n\nReview in Admin → MCP Requests."
    )
    title = (
        f"Community agent install: {len(rows)} MCP"
        f"{'s' if len(rows) != 1 else ''} need approval"
    )
    for sub in admin_subs:
        await notification_manager.fire_notification(
            title=title,
            body=body,
            severity="info",
            scope="user",
            target=sub,
            source="mcp",
            source_id=f"batch:{batch_id}",
        )


async def _maybe_notify_batch_complete(request: dict) -> None:
    """Called after a request transitions to a terminal state. If the request
    is part of a batch AND every row in the batch is now terminal, fire ONE
    follow-up notification to the requester summarizing the outcome.

    Per-MCP approve/reject notifications are suppressed for batched rows —
    the requester gets a single roll-up instead.
    """
    batch_id = request.get("batch_id")
    if not batch_id:
        return
    from storage.mcp import mcp_request_store

    all_done = await asyncio.to_thread(
        mcp_request_store.all_in_batch_terminal, batch_id,
    )
    if not all_done:
        return
    rows = await asyncio.to_thread(
        mcp_request_store.list_requests_by_batch, batch_id,
    )
    if not rows:
        return
    from services.notifications import notification_manager

    requester = rows[0]["requested_by"]
    agent_slug = rows[0]["agent_slug"]
    from storage.mcp import mcp_request_store
    installed = [r for r in rows if r["status"] == mcp_request_store.INSTALLED]
    rejected = [r for r in rows if r["status"] == mcp_request_store.REJECTED]
    cancelled = [r for r in rows if r["status"] == mcp_request_store.CANCELLED]

    lines = [f"Your community agent **{agent_slug}** is ready."]
    lines.append(
        f"{len(installed)}/{len(rows)} MCP{'s' if len(rows) != 1 else ''} approved."
    )
    if rejected:
        names = ", ".join(f"**{r['mcp_name']}**" for r in rejected)
        lines.append(f"\nRejected: {names}")
        for r in rejected:
            if (r.get("admin_note") or "").strip():
                lines.append(f"- _{r['mcp_name']}_: {r['admin_note']}")
    if cancelled:
        names = ", ".join(f"**{r['mcp_name']}**" for r in cancelled)
        lines.append(f"\nCancelled: {names}")

    severity = "info" if not (rejected or cancelled) else "warning"
    await notification_manager.fire_notification(
        title=f"Community agent {agent_slug}: setup complete",
        body="\n".join(lines),
        severity=severity,
        scope="user",
        target=requester,
        source="mcp",
        source_id=f"batch:{batch_id}",
    )


def _format_requester(request: dict) -> str:
    """Human-readable requester label for notification bodies.

    Falls back to ``Manager`` when no joined-user columns are present (e.g.
    deleted user account), or to the email when ``name`` is empty.
    """
    name = (request.get("requested_by_name") or "").strip()
    email = (request.get("requested_by_email") or "").strip()
    if name and email:
        return f"**{name}** ({email})"
    if name:
        return f"**{name}**"
    if email:
        return f"**{email}**"
    return "A manager"


async def _notify_request_approved(request: dict) -> None:
    from services.notifications import notification_manager
    await notification_manager.fire_notification(
        title="MCP request approved",
        body=(
            f"**{request['mcp_name']}** is installed and enabled for agent "
            f"**{request['agent_slug']}**."
        ),
        severity="info",
        scope="user",
        target=request["requested_by"],
        source="mcp",
        source_id=str(request["id"]),
    )


async def _notify_request_rejected(request: dict) -> None:
    from services.notifications import notification_manager
    note = request.get("admin_note") or ""
    body = f"Request for **{request['mcp_name']}** on agent **{request['agent_slug']}** was rejected."
    if note:
        body += f"\n\nAdmin note: {note}"
    await notification_manager.fire_notification(
        title="MCP request rejected",
        body=body,
        severity="warning",
        scope="user",
        target=request["requested_by"],
        source="mcp",
        source_id=str(request["id"]),
    )


async def _notify_request_failed(request: dict) -> None:
    from services.notifications import notification_manager
    log_excerpt = (request.get("install_log") or "")[:300]
    # The no-instances outcome is not a failure — the install (if any) went
    # fine and only admin instance work remains — so don't say "failed".
    # Same condition _ensure_agent_authorized_for_instance_mcp reported;
    # detected via the manifest rather than the log text so a reworded
    # guidance string can't silently break the branch.
    manifest = mcp_registry.get_manifest(request["mcp_name"])
    needs_instance = (
        manifest is not None
        and getattr(manifest, "assignment_mode", "auto") == "explicit"
    )
    if needs_instance:
        title = "MCP needs an instance"
        body = (
            f"**{request['mcp_name']}** is installed but needs an instance "
            f"before it can be enabled for **{request['agent_slug']}**. "
            f"Pick or create one from MCP Requests / MCP Servers — the "
            f"request completes automatically once an instance covers the "
            f"agent."
        )
    else:
        title = "MCP install failed"
        body = (
            f"Install failed for **{request['mcp_name']}** on agent "
            f"**{request['agent_slug']}**. The admin can retry from MCP Requests."
        )
    if log_excerpt:
        body += f"\n\n```\n{log_excerpt}\n```"
    # Notify both the requester and admins so neither side has to chase the
    # failure manually.
    targets = {request["requested_by"]}
    admin_subs = await asyncio.to_thread(_list_admin_subs)
    targets.update(admin_subs)
    for sub in targets:
        await notification_manager.fire_notification(
            title=title,
            body=body,
            # Platform severity vocabulary is info/success/warning/danger —
            # "error" renders unstyled and plays no sound.
            severity="warning",
            scope="user",
            target=sub,
            source="mcp",
            source_id=str(request["id"]),
        )


def _list_admin_subs() -> list[str]:
    """Return every admin user's ``sub``."""
    from storage.pg import get_conn
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT sub FROM users WHERE role='admin'",
        ).fetchall()
        return [r["sub"] for r in rows]
